spring:
  application:
    name:
      OrderApi
server:
  host:
    order
    #0.0.0.0
  port:
    8084
---
spring:
  config:
    activate:
      on-profile: dev
  #profiles: dev
  application:
    name: OrderApi-Dev
server:
  port: 8084