spring:
  application:
    name:
      ReportingApi
server:
  host:
    0.0.0.0
  port:
    8087
---
spring:
  config:
    activate:
      on-profile: dev
  #profiles: dev
  application:
    name: ReportingApi-Dev
server:
  port: 8087