spring:
  application:
    name:
      NotificationApi
server:
  host:
    notify
    #0.0.0.0
  port:
    8088
---
spring:
  config:
    activate:
      on-profile: dev
  #profiles: dev
  application:
    name: NotificationApi-Dev
server:
  port: 8088